cam: # cam parameters (general parameters used for all joints)
  d: 55 # (cm) robot link length; required for muscle-cam tangency calculation
  phi_range: [0, 180] # (deg) cam parameterization angle range (range for which cam geometry exists)
  beta_range: [-20, 200] # (deg) joint angle (cam) range for cam profile calculations
  beta_inc: 10 # (deg) joint angle (cam) increment for cam profile calculations

knee: # knee joint parameters
  rad0: 2.0 # (cm) cam radius at zero degrees
  slope: 0 # (cm/rad) cam profile radius slope
  theta_range: [180, 0] # (deg) joint angle theta range over which to map cam angle beta from 0 to 180  
  k_tendon: 50 # (N-cm) tendon stiffness

hip: # hip joint parameters
  rad0: 2.0
  slope: 0
  theta_range: [0, 180]
  k_tendon: 50

model: # overall robot model parameters
  joint_order: [knee_right, hip_right, hip_left, knee_left] # order of joints corresponding to below parameters
  joint_damp: [0.6, 0.8, 0.8, 0.6] # (N-m/rad/s) joint damping
  joint_damp_lims: [0, 90, 90, 0] # (deg) limits at which joint damping engages TODO: just have damping over entire range? - more realistic
  joint_stiff: [5, 15, 15, 5] # (Nm/rad) stiffness of antagonistic springs
  joint_stiff_lims:  [10, 80, 80, 10] # spring engagement starting angle
  mu: 0.999 # Coulomb foot friction coefficient

morphology: # robot morphology [shank_r, thigh_r, torso, thigh_l, shank_l]
  l: [0.4, 0.3, 0.55, 0.3, 0.4] # (m) link lengths
  m: [0.31, 0.28, 0.54, 0.28, 0.31] # (kg) robot link masses [0.31, (0.23+0.05), (0.44+2*0.05), (0.23+0.05), 0.31]
  r_cyl: 0.02 # (m) cylinder radius of each link for inertial calcs
  # J: 1/12*m*(3*r_cyl^2 + l^2); # (kg/m^2) # cylinder inertia formula

state0: # initial robot state
  # q0: [-45, 90, 45, 45, 90] # (deg)  [angle 1, knee_r, hip_r, hip_l, knee_l] initial joint angles
  # q0: [-45, 110, 25, 25, 110]
  q0: [-70, 140, 20, 20, 140]
  qd0: [0, 0, 0, 0, 0]  # (rad/s) [angle 1, knee_r, hip_r, hip_l, knee_l] initial joint velocities

control: # control parameters [knee_r, hip_r, hip_l, knee_l]
  p_max: 241.3 # (kPa) max muscle pressure
  t_musc_activate: [0.0, 0.2, 0.2, 0.0] # (sec) muscle activation timings