cam: # cam parameters (general parameters used for all joints)
  d: 55 # (cm) robot link length; required for muscle-cam tangency calculation
  phi_range: [0, 180] # (deg) cam parameterization angle range (range for which cam geometry exists)
  beta_range: [-20, 200] # (deg) joint angle (cam) range for cam profile calculations
  beta_inc: 10 # (deg) joint angle (cam) increment for cam profile calculations

knee: # knee joint parameters
  rad0: 2.0 # (cm) cam radius at zero degrees
  slope: 0 # (cm/rad) cam profile radius slope
  theta_range: [180, 0] # (deg) joint angle theta range over which to map cam angle beta from 0 to 180  
  k_tendon: 50 # (N-cm) tendon stiffness

hip: # hip joint parameters
  rad0: 2.0
  slope: 0
  theta_range: [-90, 90]
  k_tendon: 50

model: # overall robot model parameters
  joint_order: [knee_right, hip_right, hip_left, knee_left] # order of joints corresponding to below parameters
  joint_damp: [0.5, 0.5, 0.5, 0.5] # (N-m/rad/s) joint damping TODO
  joint_damp_lims: [0, 90, 90, 0]
  joint_stiff: [2.1, 2.1, 2.1, 2.1] # (Nm/rad) stiffness of antagonistic springs TODO
  #joint_stiff: [0, 0, 0, 0] # (Nm/rad) stiffness of antagonistic springs TODO
  joint_stiff_lims:  [0, 90, 90, 0] # (deg) spring engagement starting angle TODO
  mu: 0.999 # Coulomb foot friction coefficient TODO

morphology: # robot morphology [shank_r, thigh_r, torso, thigh_l, shank_l]
  l: [0.55, 0.55, 0.55, 0.55, 0.55] # (m) link lengths
  m: [0.285, 0.393, 0.858, 0.393, 0.285] # (kg) robot link masses [0.31, (0.23+0.05), (0.44+2*0.05), (0.23+0.05), 0.31] TODO
  r_cyl: 0.02 # (m) cylinder radius of each link for inertial calcs
  # J: 1/12*m*(3*r_cyl^2 + l^2); # (kg/m^2) # cylinder inertia formula

state0: # initial robot state
  q0: [0, 158, -60, -60, 158]
  qd0: [0, 0, 0, 0, 0]  # (rad/s) [angle 1, knee_r, hip_r, hip_l, knee_l] initial joint velocities

control: # control parameters [knee_r, hip_r, hip_l, knee_l]
  p_max: 206 # (kPa) max muscle pressure TODO
  t_musc_activate: [0.0, 0.0, 0.0, 0.0] # (sec) muscle activation timings

pneumatic: # pneumatic system parameters
  gas: nitrogen # gas type
  #l_tube_tank_valve: 48.0 # (in)
  #d_tube_tank_valve: 0.1875 # (in) 3/16
  l_tube_valve_musc: 48.0 # (in)
  d_tube_valve_musc: 0.1875 # (in) 3/16
  eps_tube: 15e-6 # (m)
  v_source: 0.75 # (L)
  p_source0: 60 # (psi) gauge source pressure