cam: # cam parameters (general parameters used for all 4 joints)
  d: 55 # (cm) robot link length; required for muscle-cam tangency calculation
  phi_range: [0, 180] # (deg) cam parameterization angle range (range for which cam geometry exists)
  beta_range: [-20, 200] # (deg) joint angle (cam) range for cam profile calculations
  beta_inc: 10 # (deg) joint angle (cam) increment for cam profile calculations

knee: # knee joint parameters
  rad0: 2.0 # (cm) cam radius at zero degrees
  slope: 0 # (cm/rad) cam profile radius slope
  theta_range: [180, 0] # (deg) joint angle theta range over which to map cam angle beta from 0 to 180  
  k_tendon: 100 # (N-cm) tendon stiffness TODO: characterize muscle mesh lead stiffness

hip: # hip joint parameters
  rad0: 2.0
  slope: 0
  theta_range: [-90, 90]
  k_tendon: 100 # TODO: characterize muscle mesh lead stiffness

model: # overall robot model parameters
  joint_order: [knee_right, hip_right, hip_left, knee_left] # order of joints corresponding to below parameters
  joint_damp: [0.5, 0.5, 0.5, 0.5] # (N-m/rad/s) joint damping via antagonistic springs TODO: how to determine?
  joint_damp_lims: [0, 90, 90, 0]
  joint_stiff: [2.1, 2.1, 2.1, 2.1] # (Nm/rad) stiffness of antagonistic springs: 142.8x24.0 mm nylon strip
  joint_stiff_lims:  [0, 90, 90, 0] # (deg) spring engagement starting angle TODO: adjust on robot
  mu: 0.999 # Coulomb foot friction coefficient TODO: how to determine?

morphology: # robot morphology [shank_r, thigh_r, torso, thigh_l, shank_l]
  l: [0.55, 0.55, 0.55, 0.55, 0.55] # (m) link lengths
  m: [0.285, 0.393, 0.858, 0.393, 0.285] # (kg) robot link masses: tethered robot
  r_cyl: 0.02 # (m) cylinder radius of each link for inertial calcs
  # J: 1/12*m*(3*r_cyl^2 + l^2); # (kg/m^2) # cylinder inertia formula

state0: # initial robot state
  q0: [0, 158, -60, -60, 158] # TODO: change based on design optimization
  qd0: [0, 0, 0, 0, 0]  # (rad/s) [angle 1, knee_r, hip_r, hip_l, knee_l] initial joint velocities

control: # control parameters [knee_r, hip_r, hip_l, knee_l]
  p_max: 206 # (gauge kPa) (30 psi) max muscle pressure TODO: set back to 35 psi for testing?
  t_musc_activate: [0.0, 0.0, 0.0, 0.0] # (sec) muscle activation timings

pneumatic: # pneumatic system parameters
  gas: air # gas type
  l_tube_valve_musc: 74 # (in)  ~2.0" valve fittings + 68.75" valve to muscle + ~3.2" muscle inlet tube
  d_tube_valve_musc: 0.1575 #0.1875 # (in) 3/16" ID
  eps_tube: 1e-5 # (m) TODO: how to determine? can vary from 1.5e-6 to 1e-5
  v_source: 1.475 # (L) Ninja SL 90 carbon fiber paintball tank (90 cubic in)
  p_source0: 60 # (gauge psi) source pressure TODO: adjust based on test setup